export const dbConfig = {
  API_HOST: process.env.REACT_APP_API_HOST,
  API_PORT: process.env.REACT_APP_API_PORT,
  API_BASE_URL: process.env.REACT_APP_API_BASE_URL,
};

export const FIREBASE_CONFIG = {
  API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
  AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
  STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  MESSAGING_SENDER_ID: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  APP_ID: process.env.REACT_APP_FIREBASE_APP_ID,
};

export const GOOGLE_MAPS_API_KEY = process.env.REACT_APP_GOOGLE_MAPS_API_KEY;

export const TINYMCE_API_KEY = process.env.REACT_APP_TINYMCE_API_KEY;

export const APP_NAME = process.env.REACT_APP_APP_NAME;
